# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        AppBundle\Entity\User: plaintext
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        our_db_provider:
          entity:
              class: AppBundle:User
              property: username
#        in_memory:
#            memory:
#              users:
#                ryan:
#                    password: ryanpass
#                    roles: 'ROLE_USER'
#                admin:
#                    password: kitten
#                    roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
#        secured_area:
#            logout:
#                path:   /logout
#                target: /
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: our_db_provider

            form_login:
                             login_path: /login
                             check_path: /login
            logout:
                          path:   /logout
                          target: /
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~


    access_control:
            #require ROLE_ADMIN for /admin*
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - {path: ^/rejestracja, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/, roles: ROLE_USER}


    #encoders:

    role_hierarchy:
            ROLE_ADMIN:      [ROLE_ORGANIZER, ROLE_USER]
            ROLE_SUPERADMIN: [ROLE_ADMIN]