# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    enable_generator_loggin: true;
    my_service_connection: default;
services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.message_generator:
      class: AppBundle\Service\TestController
      arguments: ['@logger','%enable_generator_loggin%']
    app.rate_recipe:
      class: AppBundle\Service\RateRecipe
      arguments: ['@doctrine.dbal.default_connection']
    app.registration:
      class: AppBundle\Service\RegistrationService
      arguments: ['@doctrine.dbal.default_connection']
