<?php
/**
 * Created by PhpStorm.
 * User: hubert
 * Date: 27.05.17
 * Time: 17:57
 */

namespace AppBundle\Form;


use AppBundle\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Email;

class RegistrationType extends AbstractType
{
 public function buildForm(FormBuilderInterface $builder, array $options)
 {
     parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
     $builder
         ->add('username', TextType::class,array('label'=>'Imie','required'=>false))
         ->add('surname',TextType::class,array('label'=>'Nazwisko','required'=>false))
         ->add('email',TextType::class,array('label'=>'Email','required'=>false))
       //  ->add('password',PasswordType::class,array('label'=>'Hasło','required'=>false))
         ->add('password', RepeatedType::class, array(
             'type' => PasswordType::class,
             'invalid_message' => 'Hasła muszą być takie same',
             'options' => array('attr' => array('class' => 'password-field')),
             'required' => true,
             'first_options'  => array('label' => 'Hasło'),
             'second_options' => array('label' => 'Powtórz hasło'),
         ))
         ->add('Zarejestruj',SubmitType::class)
         ;
 }
    public function configureOptions(OptionsResolver $resolver)
 {
     parent::configureOptions($resolver); // TODO: Change the autogenerated stub
     $resolver->setDefaults(['data_class'=>User::class]);
 }
}